"""TestCaseManager — in-process registry of review Test Cases.

Holds every Test Case so a reviewer can create, load samples, duplicate, import,
search, compare, and reopen previous ones. Each Test Case is fully isolated (its
own store instance). Only test-case *definitions* (sequence + review metadata)
are persisted, through the injected ``TestCaseSpecStore``; reasoning state is
regenerated by rerunning, deterministically.
"""

from __future__ import annotations

import os
from typing import Any

from . import samples
from .testcase import EvidenceSpec, TestCase
from .testcase_store import InMemoryTestCaseSpecStore, TestCaseSpecStore


class TestCaseManager:
    __test__ = False  # not a pytest test class despite the "Test" prefix

    def __init__(
        self,
        *,
        backend: str = "memory",
        db_base: str = "/data/sanuvia.db",
        spec_store: TestCaseSpecStore | None = None,
    ) -> None:
        self._backend = backend
        self._db_base = db_base
        self._spec_store: TestCaseSpecStore = spec_store or InMemoryTestCaseSpecStore()
        self._cases: dict[str, TestCase] = {}
        self._order: list[str] = []
        self._counter = 0
        self._current_id = ""
        self._load_saved()
        if not self._cases:
            self.new_test_case()

    # -- construction helpers ----------------------------------------------

    def _db_path_for(self, test_case_id: str) -> str:
        if self._backend != "sqlite":
            return ":memory:"
        root, ext = os.path.splitext(self._db_base)
        return f"{root}.{test_case_id}{ext or '.db'}"

    def _next_id(self) -> str:
        self._counter += 1
        return f"test-case-{self._counter}"

    def _register(self, case: TestCase) -> None:
        self._cases[case.id] = case
        self._order.append(case.id)
        self._current_id = case.id

    def _from_spec(self, spec: dict[str, Any]) -> TestCase:
        return TestCase.from_spec_dict(
            spec, backend=self._backend, db_path=self._db_path_for(str(spec["id"]))
        )

    def _load_saved(self) -> None:
        for spec in self._spec_store.load_all():
            case = self._from_spec(spec)
            self._cases[case.id] = case
            self._order.append(case.id)
            self._current_id = case.id
            suffix = case.id.rsplit("-", 1)[-1]
            if suffix.isdigit():
                self._counter = max(self._counter, int(suffix))

    # -- operations ---------------------------------------------------------

    def new_test_case(self) -> TestCase:
        tid = self._next_id()
        case = TestCase(
            id=tid, name=f"Test Case {tid.rsplit('-', 1)[-1]}",
            backend=self._backend, db_path=self._db_path_for(tid),
        )
        self._register(case)
        return case

    def duplicate_current(self) -> TestCase:
        source = self.current()
        spec = source.spec_dict()
        spec["id"] = self._next_id()
        spec["name"] = f"Copy of {source.name}"
        case = self._from_spec(spec)
        self._register(case)
        return case

    def load_sample(self, sample_id: str) -> TestCase:
        sample = samples.get_sample(sample_id)
        if sample is None:
            raise KeyError(f"unknown sample: {sample_id}")
        spec = {
            "id": self._next_id(),
            "name": sample["name"],
            "subject": "review-subject",
            "tags": list(sample["tags"]),
            "notes": [f"Loaded from sample: {sample['description']}"],
            "evidence_specs": sample["evidence_specs"],
        }
        case = self._from_spec(spec)
        self._register(case)
        return case

    def import_test_case(self, spec: dict[str, Any]) -> TestCase:
        incoming = dict(spec)
        incoming["id"] = self._next_id()  # fresh id; imported becomes editable
        incoming.setdefault("name", "Imported Test Case")
        case = self._from_spec(incoming)
        self._register(case)
        return case

    def select(self, test_case_id: str) -> TestCase:
        return self._require(test_case_id, set_current=True)

    def get(self, test_case_id: str) -> TestCase:
        return self._require(test_case_id, set_current=False)

    def _require(self, test_case_id: str, *, set_current: bool) -> TestCase:
        if test_case_id not in self._cases:
            raise KeyError(f"unknown test case: {test_case_id}")
        if set_current:
            self._current_id = test_case_id
        return self._cases[test_case_id]

    def save_current(self) -> None:
        self._spec_store.save(self.current().spec_dict())

    def current(self) -> TestCase:
        return self._cases[self._current_id]

    # -- listing & search ---------------------------------------------------

    def _summary(self, case: TestCase) -> dict[str, Any]:
        meta = case.metadata()
        return {
            "id": case.id,
            "name": case.name,
            "tags": list(case.tags),
            "created_at": case.created_at,
            "sequence_length": meta["sequence_length"],
            "interactions_run": meta["interactions_run"],
            "world_model_version": meta["world_model_version"],
            "last_exit_passed": case.last_exit_passed,
            "current": case.id == self._current_id,
        }

    def summaries(self) -> list[dict[str, Any]]:
        return [self._summary(self._cases[tid]) for tid in self._order]

    def search(self, query: str, tags: list[str] | None = None) -> list[dict[str, Any]]:
        q = query.strip().lower()
        want_tags = {t.lower() for t in (tags or [])}
        out: list[dict[str, Any]] = []
        for tid in self._order:
            case = self._cases[tid]
            haystack = [case.name.lower(), case.created_at.lower()]
            haystack += [t.lower() for t in case.tags]
            for spec in case.sequence:
                haystack.append(spec.content.lower())
                for p in spec.proposals:
                    haystack.append(p.hypothesis_id.lower())
                    haystack.append(p.statement.lower())
                haystack += [s.lower() for s in spec.supports]
                haystack += [c.lower() for c in spec.contradicts]
            text_ok = (not q) or any(q in field for field in haystack)
            tags_ok = (not want_tags) or bool(want_tags & {t.lower() for t in case.tags})
            if text_ok and tags_ok:
                out.append(self._summary(case))
        return out
