"""Built-in sample Test Cases — static engineering assets for review.

These are NOT generated by the reasoning engine. Each is a curated, deterministic
sequence of canonical EvidenceRecord specs chosen to exercise a specific engine
behaviour (competition, contradiction, failed acquisition, prediction revision,
escalation-holds, …). Loading a sample creates a new, editable Test Case copied
from the sample; the originals here are never modified.
"""

from __future__ import annotations

import copy
from typing import Any

from . import review_dataset


def _ev(
    content: str,
    evidence_class: str,
    reliability: float,
    *,
    supports: list[str] | None = None,
    contradicts: list[str] | None = None,
    proposals: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    return {
        "content": content,
        "evidence_class": evidence_class,
        "reliability": reliability,
        "source": "sample-library",
        "classification_status": "provisional",
        "supports": supports or [],
        "contradicts": contradicts or [],
        "proposals": proposals or [],
    }


def _p(hypothesis_id: str, statement: str, support: float = 0.4) -> dict[str, Any]:
    return {"hypothesis_id": hypothesis_id, "statement": statement, "initial_support": support}


_SAMPLES: list[dict[str, Any]] = [
    {
        "id": "sample-relationship-distance",
        "name": "Relationship Distance",
        "description": "One observation opens two explanations; evidence consolidates emotional distance and yields a prediction.",
        "tags": ["Relationship", "Attachment"],
        "evidence_specs": [
            _ev("partner arriving home later and quieter", "behavioural", 0.7,
                proposals=[_p("H_distance", "increasing emotional distance"),
                           _p("H_routine", "external routine change")]),
            _ev("less conversation over dinner this week", "behavioural", 0.8,
                supports=["H_distance"]),
            _ev("declined to talk about the weekend", "behavioural", 0.8,
                supports=["H_distance"]),
        ],
    },
    {
        "id": "sample-contradictory-evidence",
        "name": "Contradictory Evidence",
        "description": "An established hypothesis is contradicted, triggering an AnomalyResolution (revise).",
        "tags": ["Contradiction", "Conflict"],
        "evidence_specs": [
            _ev("thoughtful gesture after a hard day", "behavioural", 0.7,
                proposals=[_p("H_care", "partner is attentive and caring")]),
            _ev("checked in during a stressful afternoon", "behavioural", 0.8,
                supports=["H_care"]),
            _ev("planned a supportive evening", "behavioural", 0.8,
                supports=["H_care"]),
            _ev("dismissed a serious concern coldly", "contradictory", 0.8,
                contradicts=["H_care"]),
        ],
    },
    {
        "id": "sample-failed-acquisition",
        "name": "Failed Acquisition",
        "description": "A failed acquisition yields competing candidate explanations, not a single default.",
        "tags": ["Smoke Test", "Regression"],
        "evidence_specs": [
            _ev("hesitates around a particular subject", "behavioural", 0.7,
                proposals=[_p("H_topic", "avoiding a difficult topic")]),
            _ev("reflection prompt went unanswered", "failed_acquisition", 0.3,
                proposals=[_p("H_avoid", "avoiding the question itself", 0.3),
                           _p("H_stress", "an unrelated external stressor", 0.3)]),
        ],
    },
    {
        "id": "sample-competing-hypotheses",
        "name": "Competing Hypotheses",
        "description": "Two closely-supported explanations remain in competition, raising an inquiry.",
        "tags": ["Attachment", "Conflict"],
        "evidence_specs": [
            _ev("seeks closeness then pulls back", "behavioural", 0.7,
                proposals=[_p("H_anxious", "anxious attachment pattern"),
                           _p("H_avoidant", "avoidant attachment pattern")]),
            _ev("texts frequently when apart", "behavioural", 0.5,
                supports=["H_anxious"]),
        ],
    },
    {
        "id": "sample-trust-recovery",
        "name": "Trust Recovery",
        "description": "Repair strengthens while residual distrust weakens over successive evidence.",
        "tags": ["Relationship", "Regression"],
        "evidence_specs": [
            _ev("cautious after a past letdown", "reflective", 0.7,
                proposals=[_p("H_distrust", "residual distrust", 0.5),
                           _p("H_repair", "active repair underway")]),
            _ev("followed through on a promise", "behavioural", 0.8,
                supports=["H_repair"]),
            _ev("was transparent about a mistake", "behavioural", 0.8,
                supports=["H_repair"], contradicts=["H_distrust"]),
        ],
    },
    {
        "id": "sample-mixed-signals",
        "name": "Mixed Signals",
        "description": "Alternating support keeps two explanations near-tied — high uncertainty and an inquiry.",
        "tags": ["Conflict"],
        "evidence_specs": [
            _ev("warm one day, distant the next", "behavioural", 0.7,
                proposals=[_p("H_close", "wants more closeness"),
                           _p("H_space", "wants more space")]),
            _ev("initiated a long heartfelt talk", "behavioural", 0.7,
                supports=["H_close"]),
            _ev("asked for an evening alone", "behavioural", 0.7,
                supports=["H_space"]),
        ],
    },
    {
        "id": "sample-anxiety-vs-avoidance",
        "name": "Anxiety vs Avoidance",
        "description": "An anxiety reading is established then contradicted as avoidance takes the lead.",
        "tags": ["Attachment"],
        "evidence_specs": [
            _ev("pursues reassurance under stress", "behavioural", 0.7,
                proposals=[_p("H_anxiety", "anxiety-driven pursuit"),
                           _p("H_avoidance", "avoidance-driven withdrawal")]),
            _ev("escalates contact when uncertain", "behavioural", 0.8,
                supports=["H_anxiety"]),
            _ev("went silent and withdrew for days", "contradictory", 0.8,
                contradicts=["H_anxiety"], supports=["H_avoidance"]),
        ],
    },
    {
        "id": "sample-reassurance-seeking",
        "name": "Reassurance Seeking",
        "description": "A reassurance-seeking hypothesis is strengthened past threshold and yields a prediction.",
        "tags": ["Relationship", "Prediction"],
        "evidence_specs": [
            _ev("asks whether things are okay", "behavioural", 0.7,
                proposals=[_p("H_reassure", "seeks reassurance")]),
            _ev("asked several times in one evening", "behavioural", 0.85,
                supports=["H_reassure"]),
        ],
    },
    {
        "id": "sample-escalation-holds",
        "name": "Escalation (model holds)",
        "description": "A low-reliability contradiction of an established hypothesis escalates; the model holds.",
        "tags": ["Regression", "Smoke Test"],
        "evidence_specs": [
            _ev("the same argument recurs weekly", "behavioural", 0.7,
                proposals=[_p("H_cycle", "recurring conflict cycle")]),
            _ev("another instance of the cycle", "behavioural", 0.8,
                supports=["H_cycle"]),
            _ev("a third clear instance", "behavioural", 0.8,
                supports=["H_cycle"]),
            _ev("an ambiguous, low-confidence counter-signal", "contradictory", 0.3,
                contradicts=["H_cycle"]),
        ],
    },
    {
        "id": "sample-prediction-revision",
        "name": "Prediction Revision",
        "description": "A prediction is formed then invalidated when its hypothesis is contradicted.",
        "tags": ["Prediction", "Regression"],
        "evidence_specs": [
            _ev("growing quiet and distant", "behavioural", 0.7,
                proposals=[_p("H_dist", "emotional distance")]),
            _ev("fewer shared activities", "behavioural", 0.8,
                supports=["H_dist"]),
            _ev("stopped initiating contact", "behavioural", 0.8,
                supports=["H_dist"]),
            _ev("a warm, connected weekend together", "contradictory", 0.8,
                contradicts=["H_dist"]),
        ],
    },
]


def list_samples() -> list[dict[str, Any]]:
    """Browsable catalogue: id, name, description, tags, number of steps.

    Includes the quick sample scenarios plus the official engineering review
    dataset (see ``review_dataset``)."""
    quick = [
        {
            "id": s["id"],
            "name": s["name"],
            "description": s["description"],
            "tags": list(s["tags"]),
            "steps": len(s["evidence_specs"]),
        }
        for s in _SAMPLES
    ]
    return review_dataset.catalogue() + quick


def get_sample(sample_id: str) -> dict[str, Any] | None:
    """A deep copy of a sample/dataset definition (originals are never mutated)."""
    for s in _SAMPLES:
        if s["id"] == sample_id:
            return copy.deepcopy(s)
    return review_dataset.get_case(sample_id)
